description: |
  ### Document Name - SHARR-AFSBP_1.0.0_CloudTrail.4

  ## What does this document do?
  This document adds a bucket policy to restrict internet access to https only.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output

  ## Documentation Links
  * [AFSBP v1.0.0 CloudTrail.4](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-cloudtrail-4)

schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
parameters:
  Finding:
    type: StringMap
    description: The input from Step function for finding
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ""
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+'

mainSteps:
  - name: ParseInput
    action: "aws:executeScript"
    outputs:
      - Name: TrailName
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: AccountId
        Selector: $.Payload.account_id
        Type: String
    inputs:
      InputPayload:
        Finding: "{{Finding}}"
        parse_id_pattern: "^arn:(?:aws|aws-cn|aws-us-gov):cloudtrail:(?:[a-z]{2}(?:-gov)?-[a-z]+-\d):\d{12}:trail/([A-Za-z0-9._-]{3,128})$"
        expected_control_id: ["CloudTrail.4"]
      Runtime: python3.7
      Handler: parse_event
      Script: |-
        %%SCRIPT=afsbp_parse_input.py%%
    isEnd: false
  - name: Remediation
    action: "aws:executeAutomation"
    isEnd: false
    inputs:
      DocumentName: SHARR-EnableCloudTrailLogFileValidation
      RuntimeParameters:
        TrailName: "{{ParseInput.TrailName}}"
        AutomationAssumeRole: "arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-EnableCloudTrailLogFileValidation"

  - name: UpdateFinding
    action: "aws:executeAwsApi"
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
        - Id: "{{ParseInput.FindingId}}"
          ProductArn: "{{ParseInput.ProductArn}}"
      Note:
        Text: "Enabled CloudTrail log file validation."
        UpdatedBy: "SHARR-AFSBP_1.0.0_CloudTrail.3"
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
