description: |
  ### Document Name - SHARR-AFSBP_1.0.0_AutoScaling.1

  ## What does this document do?
  This document enables ELB healthcheck on a given AutoScaling Group using the [UpdateAutoScalingGroup] API.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * HealthCheckGracePeriod: (Optional) Health check grace period when ELB health check is Enabled
  Default: 30 seconds
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output

  ## Documentation Links
  * [AFSBP AutoScaling.1](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-autoscaling-1)
  
  
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - Remediation.Output
  - ParseInput.AffectedObject
parameters:
  Finding:
    type: StringMap
    description: The input from Step function for ASG1 finding
  HealthCheckGracePeriod:
    type: Integer
    default: 30
    description: ELB Health Check Grace Period
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ''
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+'
mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: AutoScalingGroupName
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):autoscaling:(?:[a-z]{2}(?:-gov)?-[a-z]+-\d):\d{12}:autoScalingGroup:(?i:[0-9a-f]{11}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}):autoScalingGroupName/(.*)$'
        expected_control_id: 'AutoScaling.1'
      Runtime: python3.7
      Handler: parse_event
      Script: |-
        %%SCRIPT=afsbp_parse_input.py%%
    isEnd: false
    
  - name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    inputs:
      DocumentName: SHARR-EnableAutoScalingGroupELBHealthCheck
      RuntimeParameters:
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-EnableAutoScalingGroupELBHealthCheck'
        AutoScalingGroupName: '{{ParseInput.AutoScalingGroupName}}'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'ASG health check type updated to ELB'
        UpdatedBy: 'SHARR-AFSBP_1.0.0_AutoScaling.1'
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
