description: |
  ### Document Name - SHARR-AFSBP_1.0.0_IAM.1

  ## What does this document do?
  This document adds a bucket policy to restrict internet access to https only.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output

  ## Documentation Links
  * [AFSBP v1.0.0 IAM.1](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-iam-1)

schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
parameters:
  Finding:
    type: StringMap
    description: The input from the Orchestrator Step function for the IAM.1 finding
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+$'

mainSteps:
  - name: ParseInput
    action: "aws:executeScript"
    outputs:
      - Name: IAMPolicy
        Selector: $.Payload.resource_id
        Type: String
      - Name: IAMResourceId
        Selector: $.Payload.details.AwsIamUser.UserId
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
      - Name: AccountId
        Selector: $.Payload.account_id
        Type: String
    inputs:
      InputPayload:
        Finding: "{{Finding}}"
        parse_id_pattern: ""
        expected_control_id: ["IAM.1"]
      Runtime: python3.8
      Handler: parse_event
      Script: |-
        %%SCRIPT=common/parse_input.py%%
    isEnd: false
  - name: Remediation
    action: "aws:executeAutomation"
    isEnd: false
    inputs:
      DocumentName: SHARR-DetachIAMPolicyFromUsers
      RuntimeParameters:
        IAMPolicy: "{{ ParseInput.IAMPolicy }}"
        AutomationAssumeRole: "arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-DetachIAMPolicyFromUsers"

  - name: UpdateFinding
    action: "aws:executeAwsApi"
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
        - Id: "{{ParseInput.FindingId}}"
          ProductArn: "{{ParseInput.ProductArn}}"
      Note:
        Text: "Added SSL-only access policy to S3 bucket."
        UpdatedBy: "SHARR-AFSBP_1.0.0_S3.5"
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
