description: |
  ### Document Name - SHARR-PCI_3.2.1_PCI.EC2.6

  ## What does this document do?
  Enables VPC Flow Logs for a VPC

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  
  ## Output Parameters
  * Remediation.Output - Remediation results

  ## Documentation Links
  * [PCI EC2.6](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-pci-controls.html#pcidss-ec2-6)
  
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output 
parameters:
  Finding:
    type: StringMap
    description: The input from Step function for finding
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ''
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+'

mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: VPC
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):ec2:.*:\d{12}:vpc/(vpc-[0-9a-f]{8,17}$)'
        expected_control_id: 'PCI.EC2.6'
      Runtime: python3.7
      Handler: parse_event
      Script: |-
        %%SCRIPT=pci_parse_input.py%%
    isEnd: false

  - name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    inputs:
      DocumentName: SHARR-EnableVPCFlowLogs
      RuntimeParameters:
        VPC: '{{ParseInput.VPC}}'
        RemediationRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-EnableVPCFlowLogs-remediationRole'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-EnableVPCFlowLogs'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Enabled VPC Flow Logs for {{ParseInput.VPC}}'
        UpdatedBy: 'SHARR-PCI_3.2.1_PCI.EC2.6'
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
