description: |
  ### Document Name - SHARR-R_CIS1.2.0_4.1

  ## What does this document do?
  Removes public access from an EC2 Security Group for controls CIS 4.1 and CIS 4.2

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output - Output of AWS-DisablePublicAccessForSecurityGroup runbook.

  ## Documentation Links
  * [R_CIS v1.2.0 4.1](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-4.1)
  * [R_CIS v1.2.0 4.2](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-4.2)

schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output
parameters:
  Finding:
    type: StringMap
    description: The input from Step function for finding
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ""
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+'

mainSteps:
  - name: ParseInput
    action: "aws:executeScript"
    outputs:
      - Name: GroupId
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: "{{Finding}}"
        parse_id_pattern: "^arn:(?:aws|aws-cn|aws-us-gov):ec2:(?:[a-z]{2}(?:-gov)?-[a-z]+-[0-9]):[0-9]{12}:security-group/(sg-[a-f0-9]{8,17})$"
        expected_control_id: ["4.1", "4.2"]
      Runtime: python3.7
      Handler: parse_event
      Script: |-
        %%SCRIPT=cis_parse_input.py%%
    isEnd: false
  - name: Remediation
    action: "aws:executeAutomation"
    isEnd: false
    inputs:
      DocumentName: AWS-DisablePublicAccessForSecurityGroup
      RuntimeParameters:
        GroupId: "{{ ParseInput.GroupId }}"
        AutomationAssumeRole: "arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-DisablePublicAccessForSecurityGroup"

  - name: UpdateFinding
    action: "aws:executeAwsApi"
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
        - Id: "{{ParseInput.FindingId}}"
          ProductArn: "{{ParseInput.ProductArn}}"
      Note:
        Text: "Disabled public access to the security group {{ ParseInput.GroupId }}."
        UpdatedBy: "SHARR-R_CIS1.2.0_4.1"
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
